name: CI
on:
  push:
    branches: ['main', 'angular-19', 'angular-18', 'angular-17', 'angular-16']
  pull_request:
    branches: ['main', 'angular-19', 'angular-18', 'angular-17', 'angular-16']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: 'test-reports/*/coverage/lcov.info'
